#!/usr/bin/env python3
"""
Script para buscar CNPJs das empresas dos familiares Vorcaro via API da Receita Federal
Uso: python buscar_cnpjs.py
"""

import requests
import time
import json
from collections import defaultdict

EMPRESAS = [
    "J RODRIGUES PLANEJAMENTO FISCAL",
    "MINI-RAPADURA IDEAL SOCIEDADE COMERCIAL LTDA",
    "3 L CONSERVADORA E SERVICOS LTDA",
    "A MANTIQUEIRA LTDA",
    "ABM INVESTIMENTOS IMOBILIARIOS LTDA",
    "ABV PARTICIPACOES LTDA",
    "ACADEMIA HEALTH PLACE LTDA",
    "ADIEL MATERIAIS DE CONSTRUCAO LTDA",
    "AFONSO SALES SERVICOS E COMERCIO LTDA",
    "AGUA E TERRA AGROPECUARIA LTDA",
    "ALLIANCE PARTICIPACOES S/A",
    "ANDREA MENDES SANCHEZ CAVALERO MEDICINA LTDA",
    "ANTONIO CARLOS TOWER LTDA",
    "APIA ASSESSORIA E CONSULTORIA ADMINISTRATIVA E IMOBILIARIA LTDA",
    "ARRAIAL PARTICIPACOES LTDA",
    "ARTHESIUM CONSULTORIA E TREINAMENTO LTDA",
    "ASCOBI ASSOCIACAO COMERCIAL DO BAIRRO DAS INDUSTRIAS",
    "ASSET ENERGY HOLDING LTDA",
    "ASSET HOLDING S.A.",
    "ASSOCIACAO COMUNITARIA DOS MORADORES LAGOA BONITA DO MUNICIPIO DE IGUATAMA MG",
    "ASSOCIACAO COMUNITARIA JACARE",
    "ASSOCIACAO EVANGELICA BETEL",
    "AUDACI IMPORTS LTDA",
    "BACHIN SERVICOS MEDICOS LTDA",
    "BANCO MASTER DE INVESTIMENTO S.A. EM LIQUIDACAO EXTRAJUDICIAL",
    "BANCO MASTER S/A EM LIQUIDACAO EXTRAJUDICIAL",
    "BAR DO CANAO LTDA",
    "BAR E LANCHONETE ESQUINAO DA BAHIA LTDA",
    "BELO PARTICIPACOES LTDA",
    "BLUE BAHIA LTDA",
    "BM ATIVIDADES IMOBILIARIAS S/A",
    "BORGES E KAISER COMERCIO DE FLORES LTDA",
    "BRUNO GERDI COMERCIAL LTDA",
    "CENTRO ODONTOLOGICO ANA BEATRIZ LTDA",
    "CENTRO SUL EMPREENDIMENTOS LTDA",
    "CITY GARDEN ARBORIZACAO URBANA LTDA",
    "CLINICA BACHIN LTDA",
    "CLUBE DE TIRO TACTICAL PARAISO VGP LTDA",
    "COMERCIAL MAGAZINE CASA BLANCA LTDA",
    "COMERCIAL SALES E ANSELMO LTDA",
    "COMISSAO PROVISORIA DO PTC JAIBA",
    "CONARTES TOWER NEGOCIOS IMOBILIARIOS LTDA",
    "CONSULTORIO MEDICO DRA GISELLE SILVA COSTA MARTINS LTDA",
    "CONTABILIDADE CHIARATO LIMITADA",
    "CSS EMPREENDIMENTOS E PARTICIPACOES LTDA",
    "DAVALOVI ENGENHARIA E CONSTRUCAO LTDA",
    "DINASTIA BOUTIQUE LTDA",
    "DINASTIA EMPREENDIMENTOS IMOBILIARIOS LTDA",
    "DINASTIA FOR MEN LTDA",
    "DINIZ ENGENHARIA SOLUCOES INDUSTRIAIS LTDA",
    "DR FELIPE DUARTE AUGUSTO NEUROCIRURGIA E DOR LTDA",
    "DV HOLDING FINANCEIRA SA",
    "EAGLES BRASIL PARTICIPACOES LTDA",
    "EAGLES VISION LTDA",
    "EBM ENGENHARIA LTDA",
    "EFAJ CONSULTORIA E ASSESSORIA EM INFORMATICA LTDA",
    "EFF CONSULTORIA IMOBILIARIA LTDA",
    "ELEICOES 2004 CF PIRANGUCU MG COMITE FINANC MUN P VEREADOR PL",
    "ELETROLUZ UBERABA LTDA",
    "EMPREENDIMENTOS DE LOCACAO OLIVEIRA SANTOS LTDA",
    "ESCOLA INFANTIL ESTRELINHAS SORRIDENTES LTDA",
    "ESPIRITO DA TERRA DISTANTE BH LTDA",
    "ESTER FERREIRA FELIPE SERVICOS LTDA",
    "EUFRATES EMPREENDIMENTOS E PARTICIPACOES LTDA",
    "EUKARYOTA PARTICIPACOES S/A",
    "FALCON BH INVESTIMENTOS LTDA",
    "FANSI BAZAR E COMERCIO LTDA",
    "FMRL SERVICOS MEDICOS LTDA",
    "GALPAO CONTAGEM PARTICIPACOES LTDA",
    "GESSO MOURA LTDA",
    "GESTACAR GESTAO DE NEGOCIOS LTDA",
    "GLOBAL MIX DESENVOLVIMENTO IMOBILIARIOS LTDA",
    "GNI11 EMPREENDIMENTOS IMOBILIARIOS S.A.",
    "GOLDEN IMOVEIS LTDA",
    "GOLDEN TOWER EMPREENDIMENTOS IMOBILIARIOS S/A",
    "GREEN HOLDING LTDA",
    "HEBRON PARTICIPACOES LTDA",
    "HEDGEHOG TRADING TECHNOLOGY INFORMATICA LTDA",
    "HELTON JONAS G. VILELA CIA LTDA",
    "HIGH LINE NEGOCIOS IMOBILIARIOS LTDA",
    "HMV PARTICIPACOES LTDA",
    "HOSPITAL JUSCELINO KUBISTCHEK LTDA",
    "HTC CULTURA EMPREENDIMENTOS E EVENTOS LTDA",
    "HV EMPREENDIMENTOS E PARTICIPACOES LTDA",
    "INFINITY PARTICIPACOES S/A",
    "INFRASOLAR HOLDING LTDA",
    "INOVACAO COMPUTACAO MOVEL LTDA",
    "INOVACAO TECNOLOGIA LTDA",
    "INTER PARTICIPACOES LTDA",
    "ISB INSTITUTO DE SAUDE BARCELOS LTDA",
    "IVANILCE DIAS MARTINS E CIA LTDA",
    "JA CONSTRUCOES PIMENTA LTDA",
    "JBLS HOLDING LTDA",
    "JULIANA SANTOS ROCHA E CIA LTDA",
    "JULICE RODRIGUES SOCIEDADE INDIVIDUAL DE ADVOCACIA",
    "JULIO LOURENCO NETO E CIA LTDA",
    "KDBRASOL AQUECEDORES SOLARES LTDA",
    "L. SANTOS ELETRICIDADE LTDA",
    "LAB ANALISES CLINICAS CONCEICAO APARECIDA S/C LTDA",
    "LABORATORIO CONCEICAO APARECIDA LTDA",
    "LAGOA ENXOVAIS LTDA",
    "LAJES PIRANGUCU LTDA",
    "LAND SPIRIT PRODUCAO DE EVENTOS LTDA",
    "LCN MERCEARIA E COMERCIO DE BEBIDAS LTDA",
    "LIFE HOLDING LTDA",
    "LX ACESSORIOS E ELETRONICOS LTDA",
    "MADEIREIRA TANQUE LTDA",
    "MAE PANIFICADORA E LANCHONETE LTDA",
    "MARAU NEGOCIOS IMOBILIARIOS LTDA",
    "MARV CONSTRUTORA LTDA",
    "MASTER HOLDING FINANCEIRA S.A.",
    "MASTER HOLDING FINANCEIRA SERVICOS S.A.",
    "MASTER PARTICIPACOES S.A.",
    "MASTER SERVICOS S.A.",
    "MC PERFORMANCE MARKETING LTDA",
    "MC SOLUCOES DIGITAIS LTDA",
    "MENDONCA BITTENCOURT PARTICIPACOES LTDA",
    "MERCATO CONSULTORIA IMOBILIARIA LTDA",
    "MERCATTO INCORPORACOES IMOBILIARIAS LTDA",
    "MILO INVESTIMENTOS S.A.",
    "MOUNTAIN II PARTICIPACOES S.A.",
    "MOUNTAIN PARTICIPACOES S.A.",
    "MULTIMAX PARTICIPACOES S/A",
    "MULTIPAR EMPREENDIMENTOS E PARTICIPACOES S.A.",
    "NA PARTICIPACOES LTDA",
    "NAVEGANTES NEGOCIOS IMOBILIARIOS LTDA",
    "NOVA IGUACU PARTICIPACOES LTDA",
    "NOVA INFORMATICA LIMITADA",
    "NOVA MAGAZINE ENXOVAIS LTDA",
    "NUCLEO DE DIAGNOSTICO EM MEDICINA S/C LTDA",
    "OLIVEIRA REPRESENTACOES LTDA",
    "ORION BH DESENVOLVIMENTO IMOBILIARIO SPE LTDA",
    "OUTLAND SOCIEDADE EMPRESARIA LTDA",
    "PACIFIC REALTY S/A",
    "PARK PARTICIPACOES S.A.",
    "PASTELARIA CHEGA MAIS LTDA",
    "PATIO DE VEICULOS VGP LTDA",
    "PHENIX TRANSPORTE RODOVIARIO DE CARGAS LTDA",
    "PIRES FOMENTO MERCANTIL LTDA",
    "PORTO HOLDING S.A.",
    "POSTO VIA NORTE LTDA",
    "PQS EMPREENDIMENTOS EDUCACIONAIS LTDA",
    "PROLIFE MG HOLDING LTDA",
    "PROSPERAR EMPREENDIMENTOS DE VENDAS LTDA",
    "RDM EMPREENDIMENTOS E COMERCIO LTDA",
    "REDE IMOBILIARIA LTDA",
    "REINO GROUP PARTICIPACOES S.A.",
    "REINO PARTICIPACOES S.A.",
    "RENATO BARROS VILELA E FILHOS LTDA",
    "RENATO TOMAIN LTDA",
    "RENOVO RECICLAGEM DE RESIDUOS LTDA",
    "REPRESENTATIVA R&F REPRESENTACOES COMERCIAIS LTDA",
    "RESTAURANTE SABOR CARIOCA LTDA",
    "RETIRO PARTICIPACOES LTDA",
    "RIO PARTICIPACOES LTDA",
    "RONIE A. T. TOMBA LTDA",
    "RRJA PLASTICOS COMERCIO E ACESSORIOS LTDA",
    "SB SOUZA COMERCIAL LTDA",
    "SGP BRASIL LTDA",
    "SHINE BAZAR E COSMETICOS LTDA",
    "SLEEPWALKERS ENTRETENIMENTO LTDA",
    "SLEEPWALKERS ENTRETENIMENTO SALVADOR LTDA",
    "SOLARIS HOTEIS LTDA",
    "SOZO PARTICIPACOES S.A.",
    "SPE CESTO INCORPORADORA S.A.",
    "STAR MUSIC LTDA",
    "SUN CLEAN DO BRASIL LTDA",
    "SUPERMERCADO MG DA ECONOMIA LTDA",
    "SUPERMERCADO YAMAMOTO LTDA",
    "SW ENTRETENIMENTO LTDA",
    "SW MASTER EVENTOS E PARTICIPACOES S/A",
    "TEIXEIRA E TOLEDO SERVICOS MEDICOS LTDA",
    "TERNI PARTICIPACOES LTDA",
    "TERRA VISTA TRANCOSO XV PARTICIPACOES LTDA",
    "TERRA VISTA TRANCOSO XVI PARTICIPACOES LTDA",
    "TIA JAQUE QUITANDAS E CAFE LTDA",
    "TOP PARTICIPACOES LTDA",
    "TOTES MANUTENCAO LTDA",
    "TRANCOSO ECO NEGOCIOS IMOBILIARIOS LTDA",
    "TRANCOSO HOLDING LTDA",
    "TRES VALES NEGOCIOS IMOBILIARIOS LTDA",
    "TROPEIRO LOCACOES LTDA",
    "TROPICAL CLUBE DE MINAS GERAIS",
    "URZEDO & SAMPAIO ADVOGADOS ASSOCIADOS",
    "VALENTINI CALCADOS E ACESSORIOS SAOJOANENSE LTDA",
    "VEM SORRIR CLINICA DO POVO LTDA",
    "VERTICE LICITA LTDA",
    "VIA EXPRESSA S/A",
    "VIDEOLAPAROSCOPIA DIAGNOSTICA E CIRURGIA DO HOSPITAL SANTA CATARINA LTDA",
    "VIKING PARTICIPACOES LTDA",
    "VINC CONSULTORIA E INVESTIMENTOS LTDA",
    "VORCARO EMPREENDIMENTOS LTDA",
    "VORCAUTO VEICULOS LTDA",
    "WEST PARTICIPACOES LTDA"
]


def buscar_cnpj_receita_federal(nome):
    """Busca CNPJ na API da Receita Federal via Selenium-like endpoint"""
    try:
        url = f"https://cnpj.pkwild.com/{nome.replace(' ', '-').lower()}"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            data = response.json()
            if data.get('results'):
                return data['results'][0].get('cnpj')
    except Exception as e:
        print(f"Erro buscando {nome}: {e}")
    return None


def main():
    resultados = {}
    print(f"Buscando CNPJs para {len(EMPRESAS)} empresas...")
    for i, empresa in enumerate(EMPRESAS):
        print(f"[{i+1}/{len(EMPRESAS)}] {empresa}")
        cnpj = buscar_cnpj_receita_federal(empresa)
        if cnpj:
            resultados[empresa] = cnpj
        time.sleep(1)

    # Salvar resultados
    with open('cnpjs_encontrados.json', 'w') as f:
        json.dump(resultoresultados, f, indent=2, ensure_ascii=False)

    print(f"\nEncontrados {len(resultados)} CNPJs")
    print("Salvo em cnpjs_encontrados.json")


if __name__ == "__main__":
    main()